# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

# Build matrix
matrix:
  include:
  - r: devel
  - r: release
  - r: oldrel
  - r: 3.4
  - r: 3.3
  - r: 3.2
  - r: 3.1

# Environment variables set for all builds
env:
  global:
  # Don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false

after_success:
  - Rscript -e 'covr::codecov()'
